apiVersion: v1
kind: Service
metadata: 
  name: mongo-db-replica-config-server
  namespace: sharding
spec: 
  selector: 
    app: mongoDB-replica-config-server
  ports:
    - protocol: TCP
      port: 27019
      targetPort: 27019
  clusterIP: None
   