apiVersion: v1
kind: Service
metadata: 
  name: mongo-db-replica
  namespace: datastores
spec: 
  selector: 
    app: mongoDB-replica
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  clusterIP: None
   