apiVersion: v1
kind: Pod
metadata:
 labels:
   run: my-pod
 name: my-pod
 namespace: jmcf
spec:
 containers:
 - image: nginx
   ports:
     - name: p1
       containerPort: 80
   name: my-pod
   resources: {}
   envFrom:
     - secretRef:
         name: s1
         optional: false
 dnsPolicy: ClusterFirst
 restartPolicy: Always
status: {}