apiVersion: v1
clusters:
- cluster:
    certificate-authority: /Users/jmcf/.minikube/ca.crt
    server: https://192.168.99.101:8443
  name: minikube
contexts:
- context:
    cluster: minikube
    namespace: jmcf
    user: minikube
  name: c2
- context:
    cluster: minikube
    user: minikube
  name: minikube
current-context: minikube
kind: Config
preferences: {}
users:
- name: minikube
  user:
    client-certificate: /Users/jmcf/.minikube/profiles/minikube/client.crt
    client-key: /Users/jmcf/.minikube/profiles/minikube/client.key